name: 'Close stale issues'

on:
  # schedule:
  #   - cron: '0 12 * * 0' # Every Sunday at 12:00 PM UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: 28
          days-before-close: 14
          days-before-pr-close: -1 # Never close PR's automatically
          only-labels: 'bug, question, Fixed for upcoming version'
          stale-issue-message: 'This issue did not receive an update in the last 4 weeks.
                                Please take a look again and update the issue with new details,
                                otherwise it will be automatically closed in 2 weeks. Thank you!'
          exempt-all-pr-milestones: true
